services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB_NAME: Traffic
      DYNAMODB_TABLE: traffic-predictor-dev-road-segments
      AWS_REGION: ap-southeast-1
      MODEL_PATH: app/notebook/TimeXer.pth
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - trafficnet
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trafficnet

volumes:
  mongo-data:

networks:
  trafficnet:
    driver: bridge
